config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'welcome#default'
  root 'welcome#index'
  get 'welcome/index'

  delete 'logout', to: 'auth#logout'
  get 'logout', to: 'auth#logout'
  get 'login', to: 'auth#login'
  post 'dologin', to: 'auth#dologin'

  get 'signup', to: 'signup#index'
  post 'signup', to: 'signup#index'
  post 'signup/save', to: 'signup#save'
  get 'signup/success', to: 'signup#success'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'

  get 'article/add'
  post 'article/save'

  get 'article/edit'
  put 'article/update'

  get 'article/delete'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsblogv1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css', media: 'all'
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #content
      .z-depth-2
        %nav
          .nav-wrapper
            %a.brand-logo{:href => "/"} &nbsp;Rails5Blog
            - if current_user
              .profilepic
                = image_tag (current_user.image_url.nil? ? "default_profile.png" : current_user.image_url), alt: current_user.name, title: current_user.name
            %ul#nav-mobile.right.hide-on-med-and-down
              - if current_user
                %li= link_to 'Add Article', article_add_path
                %li= link_to 'Sign out', logout_path, method: :delete
              - else
                %li= link_to 'Login', login_path
                %li= link_to 'Sign Up', signup_path
        .maincontent 
          = yield
  = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js'